# Generated by Django 4.0.6 on 2022-07-13 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=1)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.band')),
            ],
        ),
        migrations.DeleteModel(
            name='Design',
        ),
    ]
