# Generated by Django 4.0.6 on 2022-07-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_shirt_delete_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='design',
            field=models.CharField(max_length=100),
        ),
    ]
