# Generated by Django 4.0.6 on 2022-07-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_award_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='awards',
            field=models.ManyToManyField(to='main_app.award'),
        ),
    ]
